version: "3"

services:
  webserver:
    build: 
      context: ./bin/${PHPVERSION}
    container_name: ${WEBSERVER}
    restart: 'always'
    ports:
      - "9000:9000"
    environment:
      DOMAINS: 'law.dev'
      LETS_ENCRYPT_EMAIL: 'syed.haider@ki5.co.uk'
    links: 
      - mysql
      - es1
    volumes: 
      - ${DOCUMENT_ROOT-./app.pk}:/var/www/http
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
    networks:
    -  bm-network
      
  nginx-web: 
    container_name: nginx-web
    image: nginx
    restart: 'always'
    ports:
      - ${HOST_MACHINE_UNSECURE_HOST_PORT}:80
      - ${HOST_MACHINE_SECURE_HOST_PORT}:443
    links: 
      - mysql
      - es1
      - webserver
    volumes: 
      - ${DOCUMENT_ROOT-./app.pk}:/var/www/http
      - ${VHOSTS_DIR-./config/vhosts}:/etc/nginx/conf.d
      - ${LOG_DIR-./logs/nginx}:/var/log/nginx
      - ./certs:/etc/nginx/certs
    networks:
    -  bm-network  
  mysql:
    build: ./bin/mysql
    container_name: 'mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
    networks:
    -  bm-network  
  tilespma:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "9090:80"
    volumes: 
      - /sessions
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    networks:
    -  bm-network
  redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - "127.0.0.1:${HOST_MACHINE_REDIS_PORT}:6379"
    networks:
    -  bm-network
  es1:
    container_name: elasticsearch
    build: docker/elasticsearch/
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    networks:
    -  bm-network
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
networks:
  bm-network:
    driver: bridge